version: '3'

services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - PORT=80
      - MONGO=mongodb://root:${MONGO_PASS}@mongodb:27017/
    ports:
      - ${PORT}:80
    depends_on:
      - mongodb
  mongodb:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
